# Generated by Django 5.1 on 2025-04-24 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_cargo_unique_together_alter_cargo_hierarquia_and_more'),
        ('siape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermeta',
            name='setor',
            field=models.ForeignKey(blank=True, help_text="Selecione o setor quando a categoria for 'Setor'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.setor'),
        ),
    ]
