# Generated by Django 5.1 on 2025-04-28 20:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0002_alter_registermeta_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='registermoney',
            options={'ordering': ['-data'], 'verbose_name': 'Registro Financeiro', 'verbose_name_plural': 'Registros Financeiros'},
        ),
        migrations.AlterField(
            model_name='registermoney',
            name='data',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='registermoney',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Status (Ativo)'),
        ),
        migrations.AlterField(
            model_name='registermoney',
            name='valor_est',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Estimado/Registrado'),
        ),
        migrations.AddField(
            model_name='registermoney',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siape.produto', verbose_name='Produto'),
        ),
    ]
