# Generated by Django 5.1 on 2025-04-29 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_cargo_unique_together_alter_cargo_hierarquia_and_more'),
        ('siape', '0003_produto_alter_registermoney_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='departamento',
        ),
        migrations.AddField(
            model_name='campanha',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_siape', to='funcionarios.setor', verbose_name='Setor'),
        ),
    ]
