# Generated by Django 5.1 on 2025-04-29 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0004_remove_campanha_departamento_campanha_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='situacao_funcional',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Situação Funcional'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='debito',
            name='matricula',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Matrícula'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cpf'], name='siape_clien_cpf_9c127c_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome'], name='siape_clien_nome_acc4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['uf', 'situacao_funcional'], name='siape_clien_uf_e0bfa1_idx'),
        ),
        migrations.AddIndex(
            model_name='debito',
            index=models.Index(fields=['cliente', 'campanha'], name='siape_debit_cliente_244f04_idx'),
        ),
        migrations.AddIndex(
            model_name='debito',
            index=models.Index(fields=['matricula', 'parcela', 'prazo_restante'], name='siape_debit_matricu_8fb702_idx'),
        ),
    ]
