# Generated by Django 5.1 on 2025-04-30 11:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_comissionamento_funcionario_regras_comissionamento_and_more'),
        ('siape', '0005_alter_cliente_cpf_alter_cliente_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registermoney',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_financeiros', to='funcionarios.departamento', verbose_name='Departamento Associado'),
        ),
        migrations.AddField(
            model_name='registermoney',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_financeiros', to='funcionarios.empresa', verbose_name='Empresa Associada'),
        ),
        migrations.AddField(
            model_name='registermoney',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_financeiros', to='funcionarios.equipe', verbose_name='Equipe Associada'),
        ),
        migrations.AddField(
            model_name='registermoney',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_financeiros', to='funcionarios.setor', verbose_name='Setor Associado'),
        ),
        migrations.AlterField(
            model_name='registermoney',
            name='cpf_cliente',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='registermoney',
            name='data',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='registermoney',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.loja', verbose_name='Loja'),
        ),
        migrations.AddIndex(
            model_name='registermoney',
            index=models.Index(fields=['cpf_cliente'], name='siape_regis_cpf_cli_63fa5f_idx'),
        ),
        migrations.AddIndex(
            model_name='registermoney',
            index=models.Index(fields=['data'], name='siape_regis_data_1fb41a_idx'),
        ),
        migrations.AddIndex(
            model_name='registermoney',
            index=models.Index(fields=['user'], name='siape_regis_user_id_3f1527_idx'),
        ),
        migrations.AddIndex(
            model_name='registermoney',
            index=models.Index(fields=['loja'], name='siape_regis_loja_id_3022cb_idx'),
        ),
        migrations.AddIndex(
            model_name='registermoney',
            index=models.Index(fields=['empresa'], name='siape_regis_empresa_5761b3_idx'),
        ),
        migrations.AddIndex(
            model_name='registermoney',
            index=models.Index(fields=['departamento'], name='siape_regis_departa_99f40b_idx'),
        ),
        migrations.AddIndex(
            model_name='registermoney',
            index=models.Index(fields=['setor'], name='siape_regis_setor_i_4b3264_idx'),
        ),
        migrations.AddIndex(
            model_name='registermoney',
            index=models.Index(fields=['equipe'], name='siape_regis_equipe__42525e_idx'),
        ),
    ]
