# Generated by Django 5.1 on 2025-05-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0006_registermoney_departamento_registermoney_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('registermoney', models.OneToOneField(help_text='O registro financeiro que foi reembolsado.', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='reembolso_info', serialize=False, to='siape.registermoney', verbose_name='Registro Financeiro')),
                ('data_reembolso', models.DateField(help_text='Data em que o reembolso foi efetivado.', verbose_name='Data do Reembolso')),
                ('status', models.BooleanField(default=True, help_text='Indica que o reembolso foi efetivado (True).', verbose_name='Reembolsado')),
            ],
            options={
                'verbose_name': 'Registro de Reembolso',
                'verbose_name_plural': 'Registros de Reembolso',
                'ordering': ['-data_reembolso'],
            },
        ),
    ]
