# Generated by Django 5.1 on 2025-05-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0007_alter_arquivofuncionario_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da Campanha')),
                ('banner', models.ImageField(upload_to='banners_campanhas/', verbose_name='Banner da Campanha')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('data_final', models.DateField(verbose_name='Data Final')),
                ('hora_final', models.TimeField(verbose_name='Hora Final')),
                ('categoria', models.CharField(choices=[('GERAL', 'Geral'), ('EMPRESA', 'Empresa'), ('DEPARTAMENTO', 'Departamento'), ('SETOR', 'Setor'), ('LOJA', 'Loja'), ('EQUIPE', 'Equipe'), ('CARGO', 'Cargo')], default='GERAL', max_length=12, verbose_name='Categoria')),
                ('status', models.BooleanField(default=True, verbose_name='Status Ativo')),
                ('cargos', models.ManyToManyField(blank=True, to='funcionarios.cargo', verbose_name='Cargos')),
                ('departamentos', models.ManyToManyField(blank=True, to='funcionarios.departamento', verbose_name='Departamentos')),
                ('empresas', models.ManyToManyField(blank=True, to='funcionarios.empresa', verbose_name='Empresas')),
                ('equipes', models.ManyToManyField(blank=True, to='funcionarios.equipe', verbose_name='Equipes')),
                ('lojas', models.ManyToManyField(blank=True, to='funcionarios.loja', verbose_name='Lojas')),
                ('setores', models.ManyToManyField(blank=True, to='funcionarios.setor', verbose_name='Setores')),
            ],
            options={
                'verbose_name': 'Controle de Campanha',
                'verbose_name_plural': 'Controles de Campanhas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
