# Generated by Django 5.1 on 2025-04-23 17:50

import apps.funcionarios.models
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Horário')),
                ('entrada', models.TimeField(verbose_name='Horário de Entrada')),
                ('saida_almoco', models.TimeField(verbose_name='Saída para Almoço')),
                ('volta_almoco', models.TimeField(verbose_name='Volta do Almoço')),
                ('saida', models.TimeField(verbose_name='Horário de Saída')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Horário de Trabalho',
                'verbose_name_plural': 'Horários de Trabalho',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='funcionarios.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['empresa__nome', 'nome'],
                'unique_together': {('nome', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cargo')),
                ('hierarquia', models.IntegerField(choices=[(0, 'Padrão'), (1, 'Coordenador'), (2, 'Gerente'), (3, 'Supervisor Geral'), (4, 'Gestor'), (5, 'Superuser')], default=0, verbose_name='Nível Hierárquico')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='funcionarios.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['empresa__nome', 'hierarquia', 'nome'],
                'unique_together': {('nome', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Equipe')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('participantes', models.ManyToManyField(blank=True, related_name='equipes_participantes', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=apps.funcionarios.models.get_funcionario_upload_path, verbose_name='Foto')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gênero')),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Civil')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('celular1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular Principal')),
                ('celular2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular Secundário')),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Pai')),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade')),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naturalidade (Cidade de Nascimento)')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matrícula')),
                ('pis', models.CharField(blank=True, max_length=20, null=True, verbose_name='PIS')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='funcionarios.cargo', verbose_name='Cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='funcionarios.departamento', verbose_name='Departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='funcionarios.empresa', verbose_name='Empresa')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='funcionarios.equipe', verbose_name='Equipe')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Django')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='funcionarios.horariotrabalho', verbose_name='Horário Padrão')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['empresa__nome', 'nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\supor\\OneDrive\\Área de Trabalho\\TI Léo\\sistema\\Sistema-Money-2802\\media\\arquivos_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path, verbose_name='Arquivo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Arquivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Arquivo do Funcionário',
                'verbose_name_plural': 'Arquivos dos Funcionários',
                'ordering': ['funcionario__nome_completo', '-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.funcionarios.models.get_loja_logo_upload_path, verbose_name='Logo')),
                ('franquia', models.BooleanField(default=False, verbose_name='Franquia')),
                ('filial', models.BooleanField(default=False, verbose_name='Filial')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lojas', to='funcionarios.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['empresa__nome', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='funcionarios.loja', verbose_name='Loja'),
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setores', to='funcionarios.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['departamento__nome', 'nome'],
                'unique_together': {('nome', 'departamento')},
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='funcionarios.setor', verbose_name='Setor'),
        ),
    ]
