# Generated by Django 5.1 on 2025-04-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='hierarquia',
            field=models.IntegerField(choices=[(1, 'ESTAGIO'), (2, 'PADRAO'), (3, 'COORDENADOR(A)'), (4, 'GERENTE'), (5, 'FRANQUEADO(A)'), (6, 'SUPERVISOR(A) GERAL'), (7, 'GESTOR')], default=2, verbose_name='Nível Hierárquico'),
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together={('nome', 'empresa', 'hierarquia')},
        ),
    ]
