# Generated by Django 5.1 on 2025-04-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_cargo_unique_together_alter_cargo_hierarquia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivofuncionario',
            options={'ordering': ['funcionario_id', '-data_upload'], 'verbose_name': 'Arquivo do Funcionário', 'verbose_name_plural': 'Arquivos dos Funcionários'},
        ),
    ]
