# Generated by Django 5.1 on 2025-04-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_comissionamento_funcionario_regras_comissionamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissionamento',
            name='lojas',
            field=models.ManyToManyField(blank=True, help_text='Selecione as lojas específicas onde esta regra se aplica. Filtra dentro das empresas selecionadas (se houver).', related_name='regras_comissionamento_loja', to='funcionarios.loja', verbose_name='Lojas Aplicáveis'),
        ),
    ]
