# Generated by Django 5.1 on 2025-04-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_comissionamento_lojas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissionamento',
            name='escopo_base',
            field=models.CharField(choices=[('GERAL', 'Geral (Valor Total)'), ('EMPRESA', 'Por Empresa(s)'), ('DEPARTAMENTO', 'Por Departamento'), ('SETOR', 'Por Setor'), ('EQUIPE', 'Por Equipe'), ('PESSOAL', 'Individual (Pessoal)'), ('LOJA', 'Por Loja(s)')], default='PESSOAL', help_text="Define como o valor base para o cálculo da comissão é determinado: 'Geral' usa um valor total; 'Empresa' soma valores da(s) empresa(s) vinculada(s); 'Departamento', 'Setor', 'Equipe' somam valores da respectiva entidade; 'Pessoal' considera apenas o valor individual do funcionário.'Loja' soma valores da(s) loja(s) vinculada(s); ", max_length=20, verbose_name='Escopo da Base de Cálculo'),
        ),
    ]
