# Generated by Django 5.1 on 2025-05-07 10:45

import apps.funcionarios.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_alter_comissionamento_escopo_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivofuncionario',
            name='arquivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/moneyplus/MoneyLink-Pro/media/arquivos_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path, verbose_name='Arquivo'),
        ),
    ]
