# Generated by Django 5.1 on 2025-05-12 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_alter_arquivofuncionario_arquivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('texto', models.TextField(blank=True, verbose_name='Texto do Comunicado')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='comunicados/banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Banner')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicados_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('destinatarios', models.ManyToManyField(related_name='comunicados_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatários')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='comunicados/arquivos/', verbose_name='Arquivo')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='funcionarios.comunicado', verbose_name='Comunicado')),
            ],
            options={
                'verbose_name': 'Arquivo de Comunicado',
                'verbose_name_plural': 'Arquivos de Comunicados',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ControleComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data da Leitura')),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='funcionarios.comunicado', verbose_name='Comunicado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_comunicados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Controle de Comunicado',
                'verbose_name_plural': 'Controles de Comunicados',
                'ordering': ['-data_leitura'],
                'unique_together': {('comunicado', 'usuario')},
            },
        ),
    ]
