# Generated by Django 5.1 on 2025-05-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0008_comunicado_arquivocomunicado_controlecomunicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='loja',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='lojas',
            field=models.ManyToManyField(blank=True, related_name='funcionarios', to='funcionarios.loja', verbose_name='Lojas'),
        ),
    ]
