# Generated by Django 5.1 on 2025-06-02 17:37

import apps.funcionarios.models
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_remove_funcionario_loja_funcionario_lojas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivofuncionario',
            name='arquivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\supor\\OneDrive\\Área de Trabalho\\TI Léo\\sistema\\MoneyLink Pro\\media\\arquivos_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path, verbose_name='Arquivo'),
        ),
        migrations.CreateModel(
            name='EntradaAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('ip_usado', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Usado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_auto', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Entrada Automática',
                'verbose_name_plural': 'Entradas Automáticas',
                'ordering': ['-datahora'],
                'unique_together': {('usuario', 'data')},
            },
        ),
        migrations.CreateModel(
            name='RegistroPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo de Registro')),
                ('datahora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('entrada_auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_presenca', to='funcionarios.entradaauto', verbose_name='Entrada Automática')),
            ],
            options={
                'verbose_name': 'Registro de Presença',
                'verbose_name_plural': 'Registros de Presença',
                'ordering': ['-datahora'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioSistemaPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Relatório')),
                ('observacao', models.TextField(verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_presenca', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relatório de Presença',
                'verbose_name_plural': 'Relatórios de Presença',
                'ordering': ['-data'],
                'unique_together': {('usuario', 'data')},
            },
        ),
    ]
