# Generated by Django 5.1 on 2025-06-03 17:56

import apps.funcionarios.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_alter_arquivofuncionario_arquivo_entradaauto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('CLT', 'CLT'), ('MEI', 'MEI'), ('ESTAGIO', 'Estágio')], default='CLT', max_length=10, null=True, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='arquivofuncionario',
            name='arquivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\supor\\OneDrive\\Área de Trabalho\\TI Léo\\sistema\\MoneyLink v7\\media\\arquivos_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path, verbose_name='Arquivo'),
        ),
    ]
