# Generated by Django 5.1 on 2025-04-23 17:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('numero', models.CharField(max_length=20, verbose_name='Número de Contato')),
                ('flg_whatsapp', models.BooleanField(default=True, verbose_name='Possui WhatsApp')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cliente para Agendamento',
                'verbose_name_plural': 'Clientes para Agendamento',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('dia_agendado', models.DateTimeField(verbose_name='Data e Hora Agendada')),
                ('tabulacao_agendamento', models.TextField(blank=True, null=True, verbose_name='Tabulação do Agendamento')),
                ('atendente_agendou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inss_agendamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Atendente que Agendou')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_loja', to='funcionarios.loja', verbose_name='Loja Agendada')),
                ('cliente_agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='inss.clienteagendamento', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-dia_agendado'],
            },
        ),
        migrations.CreateModel(
            name='PresencaLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabulacao_venda', models.CharField(blank=True, choices=[('NEGOCIO FECHADO', 'NEGÓCIO FECHADO'), ('INELEGIVEL', 'INELEGÍVEL'), ('NAO ACEITOU', 'NÃO ACEITOU'), ('NAO QUIS OUVIR', 'NÃO QUIS OUVIR'), ('PENDENTE', 'PENDENTE')], max_length=50, null=True, verbose_name='Tabulação da Venda')),
                ('tipo_negociacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Negociação')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('subsidio', models.BooleanField(default=False, verbose_name='Subsídio')),
                ('valor_tac', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor TAC')),
                ('acao', models.BooleanField(default=False, verbose_name='Com Ação Judicial')),
                ('associacao', models.BooleanField(default=False, verbose_name='Com Associação')),
                ('aumento', models.BooleanField(default=False, verbose_name='Com Aumento de Margem')),
                ('status_pagamento', models.CharField(choices=[('EM ESPERA', 'EM ESPERA'), ('NAO PAGO', 'NÃO PAGO'), ('PAGO', 'PAGO')], default='EM ESPERA', max_length=20, verbose_name='Status Pagamento TAC')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Pagamento TAC')),
                ('cliente_rua', models.BooleanField(default=False, verbose_name='Cliente Veio Direto da Rua')),
                ('data_presenca', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora da Presença/Registro')),
                ('agendamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presenca', to='inss.agendamento', verbose_name='Agendamento Associado')),
                ('cliente_agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas', to='inss.clienteagendamento', verbose_name='Cliente (Rua / Sem Agendamento)')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Presença/Resultado em Loja',
                'verbose_name_plural': 'Presenças/Resultados em Loja',
                'ordering': ['-data_presenca'],
            },
        ),
    ]
