# Generated by Django 5.1 on 2025-04-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_cargo_unique_together_alter_cargo_hierarquia_and_more'),
        ('inss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencaloja',
            name='loja_comp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='presencas_loja', to='funcionarios.loja', verbose_name='Loja de Comparecimento'),
            preserve_default=False,
        ),
    ]
