# Generated by Django 5.1 on 2025-05-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inss', '0002_presencaloja_loja_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencaloja',
            name='status_pagamento',
            field=models.CharField(choices=[('EM_ESPERA', 'EM ESPERA'), ('NAO_PAGO', 'NÃO PAGO'), ('PAGO', 'PAGO')], default='EM_ESPERA', max_length=20, verbose_name='Status Pagamento TAC'),
        ),
    ]
