# Generated by Django 5.1 on 2025-05-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inss', '0003_alter_presencaloja_status_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencaloja',
            name='tabulacao_venda',
            field=models.CharField(blank=True, choices=[('NEGOCIO_FECHADO', 'NEGÓCIO FECHADO'), ('INELEGIVEL', 'INELEGÍVEL'), ('NAO_ACEITOU', 'NÃO ACEITOU'), ('NAO_QUIS_OUVIR', 'NÃO QUIS OUVIR'), ('PENDENTE', 'PENDENTE')], max_length=20, null=True, verbose_name='Tabulação da Venda'),
        ),
    ]
