# Generated by Django 5.1 on 2025-05-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inss', '0005_alter_presencaloja_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status_atendimento',
            field=models.CharField(choices=[('EM_ATENDIMENTO', 'EM ATENDIMENTO'), ('FINALIZADO', 'FINALIZADO'), ('AGUARDANDO', 'AGUARDANDO')], default='AGUARDANDO', max_length=20, verbose_name='Status do Atendimento'),
        ),
    ]
