# Generated by Django 5.1 on 2025-05-28 17:40

import apps.juridico.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0009_remove_funcionario_loja_funcionario_lojas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(db_index=True, max_length=14, unique=True, verbose_name='CPF')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Cliente da Ação',
                'verbose_name_plural': 'Clientes das Ações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('ASSOCIACAO', 'Associação'), ('CARTAO', 'Cartão'), ('DEBITO_CONTA', 'Débito em Conta'), ('LIMPANOME', 'Limpanome'), ('REVISIONAL', 'Revisional')], max_length=50, verbose_name='Tipo de Ação')),
                ('status_emcaminhamento', models.CharField(choices=[('EM_ESPERA', 'Em Espera'), ('INCOMPLETO', 'Incompleto'), ('EM_DESPACHO', 'Em Despacho'), ('PROTOCOLADO', 'Protocolado'), ('FINALIZADO', 'Finalizado')], default='EM_ESPERA', max_length=50, verbose_name='Status em Caminhamento')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Atualização')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('motivo_cancelamento', models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento')),
                ('numero_protocolo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Protocolo')),
                ('motivo_incompleto', models.TextField(blank=True, null=True, verbose_name='Motivo da Incompletude')),
                ('status', models.BooleanField(default=True, verbose_name='Status Ativo')),
                ('motivo_inatividade', models.TextField(blank=True, null=True, verbose_name='Motivo da Inatividade')),
                ('senha_inss', models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha INSS')),
                ('sentenca', models.CharField(blank=True, choices=[('FAVORAVEL', 'Favorável'), ('NAO_FAVORAVEL', 'Não Favorável'), ('PENDENTE', 'Pendente')], max_length=20, null=True, verbose_name='Sentença')),
                ('grau_sentenca', models.CharField(blank=True, choices=[('PRIMEIRO_GRAU', 'Primeiro Grau'), ('SEGUNDO_GRAU', 'Segundo Grau')], max_length=20, null=True, verbose_name='Grau da Sentença')),
                ('valor_sentenca', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Sentença')),
                ('data_sentenca', models.DateField(blank=True, null=True, verbose_name='Data da Sentença')),
                ('recurso_primeiro_grau', models.CharField(blank=True, choices=[('NENHUM', 'Nenhum'), ('APELACAO', 'Apelação'), ('AGRAVO', 'Agravo'), ('EMBARGOS', 'Embargos')], default='NENHUM', max_length=20, null=True, verbose_name='Recurso 1º Grau')),
                ('data_recurso_primeiro_grau', models.DateField(blank=True, null=True, verbose_name='Data do Recurso 1º Grau')),
                ('resultado_recurso_primeiro_grau', models.CharField(blank=True, choices=[('FAVORAVEL', 'Favorável'), ('NAO_FAVORAVEL', 'Não Favorável'), ('PENDENTE', 'Pendente')], max_length=20, null=True, verbose_name='Resultado do Recurso 1º Grau')),
                ('recurso_segundo_grau', models.CharField(blank=True, choices=[('NENHUM', 'Nenhum'), ('APELACAO', 'Apelação'), ('AGRAVO', 'Agravo'), ('EMBARGOS', 'Embargos')], default='NENHUM', max_length=20, null=True, verbose_name='Recurso 2º Grau')),
                ('data_recurso_segundo_grau', models.DateField(blank=True, null=True, verbose_name='Data do Recurso 2º Grau')),
                ('resultado_recurso_segundo_grau', models.CharField(blank=True, choices=[('FAVORAVEL', 'Favorável'), ('NAO_FAVORAVEL', 'Não Favorável'), ('PENDENTE', 'Pendente')], max_length=20, null=True, verbose_name='Resultado do Recurso 2º Grau')),
                ('advogado_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_advogado', to=settings.AUTH_USER_MODEL, verbose_name='Advogado Responsável')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_loja', to='funcionarios.loja', verbose_name='Loja')),
                ('vendedor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Responsável')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.clienteacao', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ArquivosAcoesINSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=255, verbose_name='Título do Arquivo')),
                ('data_import', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Importação')),
                ('file', models.FileField(upload_to=apps.juridico.models._upload_to_arquivo_acoes, verbose_name='Arquivo')),
                ('acao_inss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='juridico.acoes', verbose_name='Ação INSS')),
            ],
            options={
                'verbose_name': 'Arquivo de Ação INSS',
                'verbose_name_plural': 'Arquivos de Ações INSS',
                'ordering': ['-data_import'],
            },
        ),
        migrations.CreateModel(
            name='DocsAcaoINSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=255, verbose_name='Título do Documento')),
                ('data_import', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Importação')),
                ('file', models.FileField(upload_to=apps.juridico.models._upload_to_documento_acoes, verbose_name='Documento')),
                ('acao_inss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='juridico.acoes', verbose_name='Ação INSS')),
            ],
            options={
                'verbose_name': 'Documento de Ação INSS',
                'verbose_name_plural': 'Documentos de Ações INSS',
                'ordering': ['-data_import'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagamento', models.CharField(choices=[('A_VISTA', 'À Vista'), ('PARCELADO', 'Parcelado'), ('ENTRADA_PARCELAS', 'Entrada + Parcelas')], default='A_VISTA', help_text='Forma de pagamento escolhida', max_length=20, verbose_name='Tipo de Pagamento')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total')),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Entrada')),
                ('parcelas_totais', models.IntegerField(default=0, help_text='Número total de parcelas do pagamento', verbose_name='Total de Parcelas')),
                ('parcelas_pagas', models.IntegerField(default=0, verbose_name='Parcelas Pagas')),
                ('parcelas_restantes', models.IntegerField(default=0, verbose_name='Parcelas Restantes')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('QUITADO', 'Quitado'), ('CANCELADO', 'Cancelado')], db_index=True, default='EM_ANDAMENTO', max_length=20, verbose_name='Status do Pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('acao_inss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pagamento', to='juridico.acoes', verbose_name='Ação INSS')),
            ],
            options={
                'verbose_name': 'Registro de Pagamento',
                'verbose_name_plural': 'Registros de Pagamento',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPagamentosFeitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('parcela_paga', models.IntegerField(blank=True, help_text='Número da parcela paga (opcional para pagamentos à vista)', null=True, verbose_name='Número da Parcela')),
                ('flg_atrasado', models.BooleanField(default=False, verbose_name='Pagamento Atrasado')),
                ('flg_acordo', models.BooleanField(default=False, verbose_name='Pagamento com Acordo')),
                ('tipo_acordo', models.CharField(choices=[('NENHUM', 'Nenhum'), ('DESCONTO', 'Desconto no Valor'), ('PARCELAMENTO', 'Novo Parcelamento'), ('QUITACAO', 'Quitação com Desconto')], default='NENHUM', max_length=20, verbose_name='Tipo de Acordo')),
                ('juros_atrasado_mensal', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de juros aplicado por atraso mensal (0-100)', max_digits=5, verbose_name='Juros por Atraso Mensal (%)')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('observacao', models.TextField(blank=True, help_text='Observações sobre o pagamento ou acordo', null=True, verbose_name='Observação')),
                ('registro_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_feitos', to='juridico.registropagamentos', verbose_name='Registro de Pagamento')),
            ],
            options={
                'verbose_name': 'Registro de Pagamento Feito',
                'verbose_name_plural': 'Registros de Pagamentos Feitos',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
