# Generated by Django 5.1 on 2025-06-05 16:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, help_text='Armazenada em UTC, exibida no timezone local', verbose_name='Data de Criação')),
                ('status', models.BooleanField(default=True, verbose_name='Status Ativo')),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='orgao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='marketing.orgao', verbose_name='Órgão'),
            preserve_default=False,
        ),
    ]
