# Generated by Django 5.1 on 2025-05-04 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('APP', 'Categoria - APP'), ('RENDER', 'SubCategoria - Render/Template'), ('SECTION', 'Sessão - Section/Container'), ('DIV', 'SubSessão - Div/Content'), ('BOX', 'Caixa - div/span/box/card')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControleAcessos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('acessos', models.ManyToManyField(related_name='usuarios_controle', to='usuarios.acesso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controle_acessos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupsAcessos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('acessos', models.ManyToManyField(related_name='groups_acessos', to='usuarios.acesso')),
            ],
        ),
    ]
