# Generated by Django 5.1 on 2025-05-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='tipo',
            field=models.CharField(choices=[('CT', 'Categoria - APP'), ('SCT', 'SubCategoria - Render/Template'), ('SS', 'Sessão - Section/Container'), ('SSS', 'SubSessão - Div/Content'), ('CX', 'Caixa - div/span/box/card')], max_length=20),
        ),
    ]
