# Generated by Django 5.1 on 2025-05-23 11:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_acesso_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('audio', models.FileField(upload_to='alertas/audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])], verbose_name='Áudio de Alerta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_ti_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('destinatarios', models.ManyToManyField(related_name='alertas_ti_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatários')),
            ],
            options={
                'verbose_name': 'Alerta TI',
                'verbose_name_plural': 'Alertas TI',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
