# Generated by Django 5.1 on 2025-05-23 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alertati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertati',
            name='audio',
            field=models.FileField(upload_to='alertas/audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'mpeg', 'mpeg4'])], verbose_name='Áudio de Alerta'),
        ),
    ]
